import { describe, expect, it, jest } from '@jest/globals';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  canonicalJson, canonicalTimestamp, nonCanonicalTimestamps, parseExportLines, parseJson, StrictJsonError,
  verifyAgreement, verifyBoundaryDecision, verifyDataAccessIntent,
} from '../src/index.js';
import { decodeUtf8 } from '../src/strict-json.js';
import { buildTransport } from './helpers.js';
import type { AgreementRecord, BoundaryDecision, DataAccessIntent, DataLicensePolicy } from '../src/index.js';

/**
 * Shared conformance suite `canonical` (v1.2.0), generated by the Python
 * reference (genesismesh/conformance/generate_vectors.py canonical) and copied
 * unchanged: input every implementation reads alike or refuses by reason, and
 * the canonical form of records.
 */
interface Vector { id: string; kind: string; input: unknown; expected: Record<string, unknown> }
const raw = readFileSync(fileURLToPath(new URL('./fixtures/conformance/canonical.json', import.meta.url)), 'utf-8');
const suite = parseJson(raw) as { vectors: Vector[] };

describe('canonical conformance suite', () => {
  it('has every kind of case', () => {
    const kinds = new Set(suite.vectors.map(v => v.kind));
    expect([...kinds].sort()).toEqual(['json', 'timestamp', 'verify_agreement', 'verify_decision', 'verify_intent']);
  });

  it.each(suite.vectors.map(v => [v.id, v] as const))('%s', (_id, v) => {
    const input = v.input as Record<string, unknown>;
    switch (v.kind) {
      case 'json': {
        let got: Record<string, unknown>;
        try {
          got = { canonical: canonicalJson(parseJson(v.input as string)) };
        } catch (err) {
          if (!(err instanceof StrictJsonError)) throw err;
          got = { refused: err.reason };
        }
        expect(got).toEqual(v.expected);
        break;
      }
      case 'timestamp':
        expect({ canonical: canonicalTimestamp(v.input) }).toEqual(v.expected);
        break;
      case 'verify_decision': {
        const r = verifyBoundaryDecision(input['decision'] as BoundaryDecision, {
          operatorPublicKeys: input['operator_public_keys'] as string[], now: new Date(input['now'] as string),
        });
        expect({ accepted: r.accepted, reason: r.reason }).toEqual(v.expected);
        break;
      }
      case 'verify_agreement': {
        const r = verifyAgreement(input['agreement'] as AgreementRecord,
          input['offerer_public_keys'] as string[], input['responder_public_keys'] as string[]);
        expect({ accepted: r.accepted, reason: r.reason }).toEqual(v.expected);
        break;
      }
      case 'verify_intent': {
        const r = verifyDataAccessIntent(input['intent'] as DataAccessIntent, input['policy'] as DataLicensePolicy,
          input['agent_public_keys'] as string[], input['at'] as string);
        expect({ detail: r.violations[0]?.detail ?? null }).toEqual(v.expected);
        break;
      }
      default:
        throw new Error(`unknown kind ${v.kind}`);
    }
  });

  it('names the timestamp paths, at any depth', () => {
    const agreement = suite.vectors.find(v => v.id === 'verify-agreement-signed-non-canonical-timestamp')!;
    expect(nonCanonicalTimestamps('AgreementRecord', (agreement.input as Record<string, unknown>)['agreement']))
      .toEqual(['agreed_terms.valid_from']);
  });

  it('refuses ambiguous input in HTTP responses and exports too', async () => {
    expect(() => parseJson('{"status":"ok","status":"no"}')).toThrow(StrictJsonError);
    const respond = (body: BodyInit) => jest.fn<typeof globalThis.fetch>().mockResolvedValue(new Response(body, { status: 200 }));
    await expect(buildTransport(respond('{"status":"ok","status":"no"}')).publicGet('/health'))
      .rejects.toMatchObject({ name: 'StrictJsonError', reason: 'duplicate_key', code: 'duplicate_key' });
    // A body that is not JSON, or not UTF-8, stays a NetworkError, as before.
    await expect(buildTransport(respond(new Uint8Array([0x7b, 0x22, 0xff, 0x22, 0x3a, 0x31, 0x7d]))).publicGet('/health'))
      .rejects.toMatchObject({ name: 'NetworkError' });
    await expect(buildTransport(respond(new Uint8Array([0xef, 0xbb, 0xbf, 0x7b, 0x7d]))).publicGet('/health'))
      .rejects.toMatchObject({ name: 'NetworkError' });
    expect(decodeUtf8(new Uint8Array([0xef, 0xbb, 0xbf, 0x7b, 0x7d]))).toBe('\ufeff{}');
    expect(() => decodeUtf8(new Uint8Array([0xff]))).toThrow(StrictJsonError);
  });

  it('strips only JSON whitespace around export lines', () => {
    expect(parseExportLines(' \t\r\n')).toEqual([]);
    expect(() => parseExportLines('\u00a0{}')).toThrow(StrictJsonError);
    expect(() => parseExportLines('\ufeff{}')).toThrow(StrictJsonError);
  });
});
