import { describe, expect, it } from '@jest/globals';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  CANONICAL_REGISTRY, isKnownEntryKind, parseJson, unknownFields, verifyAgreement, verifyBoundaryDecision,
  verifyEvidenceEvents,
} from '../src/index.js';
import type { AgreementRecord, BoundaryDecision, EvidenceEvent } from '../src/index.js';

/**
 * Shared conformance suite `canonical` (v1.2.0), generated by the Python
 * reference (genesismesh/conformance/generate_vectors.py canonical) and copied
 * unchanged: the field registry of signed records and the fields every
 * verifier refuses.
 */
interface Vector {
  id: string; kind: string; model?: string; record?: unknown; entry_kind?: string;
  expected: { unknown_fields?: string[]; known?: boolean };
}
const raw = readFileSync(fileURLToPath(new URL('./fixtures/conformance/canonical.json', import.meta.url)), 'utf-8');
const suite = parseJson(raw) as { registry: unknown; vectors: Vector[] };
const interop = parseJson(readFileSync(fileURLToPath(new URL('./fixtures/conformance/interop.json', import.meta.url)), 'utf-8')) as
  { vectors: Array<{ id: string; input: Record<string, unknown> }> };
const input = (id: string) => interop.vectors.find(v => v.id === id)!.input;

describe('canonical conformance suite', () => {
  it('embeds the registry of the suite (run npm run sync:registry after copying a new suite)', () => {
    expect(CANONICAL_REGISTRY).toEqual(suite.registry);
  });

  it.each(suite.vectors.map(v => [v.id, v] as const))('%s', (_id, v) => {
    if (v.kind === 'unknown_fields') {
      expect({ unknown_fields: unknownFields(v.model!, v.record).sort() }).toEqual(v.expected);
    } else {
      expect({ known: isKnownEntryKind(v.entry_kind) }).toEqual(v.expected);
    }
  });
});

describe('verifiers refuse fields they do not know', () => {
  const decisionInput = input('bd-003');
  const decision = decisionInput['decision'] as BoundaryDecision;
  const options = {
    operatorPublicKeys: decisionInput['operator_public_keys'] as string[],
    now: new Date(decisionInput['now'] as string),
  };

  it('a decision with a signed field from a later release', () => {
    expect(verifyBoundaryDecision(decision, options).reason).toBe('authorized');
    const later = { ...decision, risk_tier: 'high' } as unknown as BoundaryDecision;
    expect(verifyBoundaryDecision(later, options)).toMatchObject({ accepted: false, reason: 'unknown_field' });
  });

  it('a nested unknown field and an expected policy with one', () => {
    const nested = JSON.parse(JSON.stringify(decision)) as BoundaryDecision & { policy_binding: Record<string, unknown> };
    nested.policy_binding['x'] = 1;
    expect(verifyBoundaryDecision(nested, options).reason).toBe('unknown_field');
    const policies = (decisionInput['expected_policies'] as Array<Record<string, unknown>>).map(p => ({ ...p, x: 1 }));
    expect(verifyBoundaryDecision(decision, { ...options, expectedPolicies: policies as never }).reason).toBe('unknown_field');
  });

  it('an agreement', () => {
    const agr = input('agr-001');
    const record = { ...(agr['agreement'] as AgreementRecord), x: 1 } as AgreementRecord;
    expect(verifyAgreement(record, agr['offerer_public_keys'] as string[], agr['responder_public_keys'] as string[]).reason)
      .toBe('unknown_field');
  });

  it('an export entry of an unknown kind, and a payload with an unknown field', () => {
    const entry = (kind: string, seq: number) => ({
      schema: 'gm.evidence.event', schema_version: 1, entry_digest: 'x', payload: { x: 1 },
      entry: { store_sequence: seq, entry_kind: kind, recorded_at: '2026-01-01T00:00:00Z', payload_digest: 'p', prev_entry_digest: null,
        decision_id: null, context_id: null, vendor_id: null, attestation_id: null, capability: null, outcome: null,
        evidence_id: null, executor_sovereign_id: null, exec_sequence_no: null, resource_id: null, resource_action: null,
        resource_sequence: null },
    }) as unknown as EvidenceEvent;
    const result = verifyEvidenceEvents([entry('observation', 1), entry('justification', 2)], { naPublicKeys: [], executorKeys: [] });
    const reasons = result.failures.map(f => `${f.store_sequence}:${f.reason}`);
    expect(reasons).toContain('1:unknown_entry_kind');
    expect(reasons).toContain('2:unknown_field');
  });
});
