import { describe, expect, it } from '@jest/globals';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  canonicalJson, parseJson, verifyAgreement, verifyBoundaryDecision, verifyDataAccessIntent,
  verifyDataLicensePolicySignature, createDataAccessIntent, seedSigner, publicKeyFromSeed,
} from '../src/index.js';
import type {
  AgreementRecord, BoundaryDecision, BoundaryPolicy, DataAccessIntent, DataLicensePolicy, MembershipAttestation,
} from '../src/index.js';
import { generateTestKeyPair } from './helpers.js';

/**
 * Shared conformance vectors generated by the Python reference
 * (genesismesh/conformance/generate_vectors.py interop), copied unchanged.
 * Go and .NET run the same file; every vector must give the reference outcome.
 */
interface Vector { id: string; kind: string; description: string; input: Record<string, unknown>; expected: Record<string, unknown> }

const raw = readFileSync(fileURLToPath(new URL('./fixtures/conformance/interop.json', import.meta.url)), 'utf-8');
// parseJson keeps integral floats (1.0) so signatures over them still verify.
const suite = parseJson(raw) as { suite: string; vectors: Vector[] };

function outcome(v: Vector): Record<string, unknown> {
  const i = v.input;
  switch (v.kind) {
    case 'canonical_json':
      return { canonical: canonicalJson(parseJson(i['json'] as string)) };
    case 'agreement': {
      const r = verifyAgreement(i['agreement'] as AgreementRecord, i['offerer_public_keys'] as string[],
        i['responder_public_keys'] as string[], i['expected_graph_digest'] as string | undefined);
      return { accepted: r.accepted, reason: r.reason };
    }
    case 'boundary_decision': {
      const r = verifyBoundaryDecision(i['decision'] as BoundaryDecision, {
        operatorPublicKeys: i['operator_public_keys'] as string[],
        now: new Date(i['now'] as string),
        ...(i['expected_policies'] ? { expectedPolicies: i['expected_policies'] as BoundaryPolicy[] } : {}),
        ...(i['expected_attestation'] ? { expectedAttestation: i['expected_attestation'] as MembershipAttestation } : {}),
      });
      return { accepted: r.accepted, reason: r.reason, authorized: r.authorized };
    }
    case 'data_license_policy':
      return { valid: verifyDataLicensePolicySignature(i['policy'] as DataLicensePolicy, i['licensor_public_keys'] as string[]) };
    case 'data_access_intent': {
      const r = verifyDataAccessIntent(i['intent'] as DataAccessIntent, i['policy'] as DataLicensePolicy,
        i['agent_public_keys'] as string[], i['at'] as string);
      return { valid: r.valid, violation_reason: r.violation_reason, violation_types: r.violations.map(x => x.violation_type) };
    }
    default:
      throw new Error(`unknown vector kind ${v.kind}`);
  }
}

describe('interop conformance vectors (v0.61)', () => {
  it('is the interop suite and covers every artifact kind', () => {
    expect(suite.suite).toBe('interop');
    expect(new Set(suite.vectors.map(v => v.kind))).toEqual(
      new Set(['canonical_json', 'agreement', 'boundary_decision', 'data_license_policy', 'data_access_intent']));
  });

  it.each(suite.vectors.map(v => [v.id, v] as const))('%s reproduces the reference outcome', (_id, v) => {
    expect(outcome(v)).toEqual(v.expected);
  });
});

describe('createDataAccessIntent', () => {
  const policyVector = suite.vectors.find(v => v.id === 'int-001')!;
  const policy = policyVector.input['policy'] as DataLicensePolicy;
  const at = policyVector.input['at'] as string;

  it('signs an intent that verifies offline, in the reference form', async () => {
    const agent = generateTestKeyPair();
    const intent = await createDataAccessIntent({
      agent_sovereign_id: 'sovereign-b', decision_id: 'dec-1', access_types: ['read'], estimated_volume_bytes: 2048,
      sources: [{ source_id: 'db-prod', source_type: 'proprietary', owner_sovereign_id: 'sovereign-a', classification_tags: [] }],
      valid_for_seconds: 3600, now: new Date('2026-01-01T00:30:00.123Z'),
    }, seedSigner(agent.seedBase64, 'sovereign-b'));
    expect(intent.declared_at).toBe('2026-01-01T00:30:00.123000Z');
    expect(intent.expires_at).toBe('2026-01-01T01:30:00.123000Z');
    expect(intent.signature?.key_id).toBe('sovereign-b');
    expect(verifyDataAccessIntent(intent, policy, [publicKeyFromSeed(agent.seedBase64)], at)).toEqual(
      { valid: true, violation_reason: null, violations: [] });
    const other = generateTestKeyPair();
    expect(verifyDataAccessIntent(intent, policy, [other.pubBase64], at).violation_reason).toBe('intent_exceeds_license');
  });

  it('refuses a non-positive validity', async () => {
    const agent = generateTestKeyPair();
    await expect(createDataAccessIntent({ agent_sovereign_id: 'a', decision_id: 'd', sources: [], access_types: [],
      valid_for_seconds: 0 }, seedSigner(agent.seedBase64, 'a'))).rejects.toThrow();
  });
});
