import { describe, expect, it } from '@jest/globals';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  isKnownEntryKind, parseExportLines, parseJson, unknownFields, verifyAgreement, verifyBoundaryDecision,
  verifyEvidenceEvents,
} from '../src/index.js';
import type { AgreementRecord, BoundaryDecision } from '../src/index.js';
import { CANONICAL_REGISTRY } from '../src/canonical-registry.js';
import {
  AGREEMENT_CANONICAL_FIELDS,
  CHECKPOINT_OMITTED_WHEN_ABSENT,
  DECISION_OMITTED_WHEN_ABSENT,
  ENVELOPE_OMITTED_WHEN_ABSENT,
  RESOURCE_CHAIN_FIELDS,
} from '../src/canonical.js';

/**
 * Shared conformance suite `field_registry` (v1.2.0), generated by the Python
 * reference (genesismesh/conformance/generate_vectors.py field_registry) and
 * copied unchanged: the field registry of signed records and the fields every
 * verifier refuses.
 */
interface Vector {
  id: string; kind: string; model?: string; record?: unknown; entry_kind?: string;
  input?: Record<string, unknown>; expected: Record<string, unknown>;
}
const raw = readFileSync(fileURLToPath(new URL('./fixtures/conformance/field_registry.json', import.meta.url)), 'utf-8');
const suite = parseJson(raw) as { registry: typeof CANONICAL_REGISTRY; vectors: Vector[] };

describe('field_registry conformance suite', () => {
  it('embeds the registry of the suite (run npm run sync:registry after copying a new suite)', () => {
    expect(CANONICAL_REGISTRY).toEqual(suite.registry);
    expect(Object.isFrozen(CANONICAL_REGISTRY.models['BoundaryDecision']!.fields)).toBe(true);
  });

  it("keeps this SDK's canonical rules equal to the registry's", () => {
    const models = CANONICAL_REGISTRY.models;
    expect([...RESOURCE_CHAIN_FIELDS]).toEqual(models['ExecutionEvidence']!.omit_when_none);
    expect([...DECISION_OMITTED_WHEN_ABSENT]).toEqual(models['BoundaryDecision']!.omit_when_none);
    expect([...ENVELOPE_OMITTED_WHEN_ABSENT]).toEqual(models['EvidenceStoreEntry']!.omit_when_none);
    expect([...CHECKPOINT_OMITTED_WHEN_ABSENT]).toEqual(models['RetentionCheckpoint']!.omit_when_none);
    expect([...AGREEMENT_CANONICAL_FIELDS]).toEqual(models['AgreementRecord']!.canonical_fields);
  });

  it.each(suite.vectors.map(v => [v.id, v] as const))('%s', (_id, v) => {
    const input = v.input ?? {};
    switch (v.kind) {
      case 'unknown_fields':
        expect({ unknown_fields: unknownFields(v.model!, v.record) }).toEqual(v.expected);
        break;
      case 'entry_kind':
        expect({ known: isKnownEntryKind(v.entry_kind) }).toEqual(v.expected);
        break;
      case 'verify_decision': {
        const r = verifyBoundaryDecision(input['decision'] as BoundaryDecision, {
          operatorPublicKeys: input['operator_public_keys'] as string[], now: new Date(input['now'] as string),
        });
        expect({ accepted: r.accepted, reason: r.reason }).toEqual(v.expected);
        break;
      }
      case 'verify_agreement': {
        const r = verifyAgreement(input['agreement'] as AgreementRecord,
          input['offerer_public_keys'] as string[], input['responder_public_keys'] as string[]);
        expect({ accepted: r.accepted, reason: r.reason }).toEqual(v.expected);
        break;
      }
      case 'export': {
        const result = verifyEvidenceEvents(parseExportLines(input['lines'] as string), { naPublicKeys: [], executorKeys: [] });
        expect({ failures: result.failures.map(f => ({ store_sequence: f.store_sequence, reason: f.reason })) }).toEqual(v.expected);
        break;
      }
      default:
        throw new Error(`unknown kind ${v.kind}`);
    }
  });
});

describe('verifiers refuse signed fields they do not know', () => {
  const vectors = Object.fromEntries(suite.vectors.map(v => [v.id, v]));

  it('an expected policy with an unknown field', () => {
    const interop = parseJson(readFileSync(fileURLToPath(new URL('./fixtures/conformance/interop.json', import.meta.url)), 'utf-8')) as
      { vectors: Array<{ id: string; input: Record<string, unknown> }> };
    const bd = interop.vectors.find(v => v.id === 'bd-001')!.input;
    const opts = { operatorPublicKeys: bd['operator_public_keys'] as string[], now: new Date(bd['now'] as string) };
    const policies = bd['expected_policies'] as Array<Record<string, unknown>>;
    expect(verifyBoundaryDecision(bd['decision'] as BoundaryDecision, { ...opts, expectedPolicies: policies as never }).accepted)
      .toBe(true);
    const withField = policies.map(p => ({ ...p, x: 1 }));
    expect(verifyBoundaryDecision(bd['decision'] as BoundaryDecision, { ...opts, expectedPolicies: withField as never }).reason)
      .toBe('unknown_field');
  });

  it('a following entry still chains after an unknown kind', () => {
    const line = vectors['export-unknown-entry-kind']!.input!['lines'] as string;
    const result = verifyEvidenceEvents([...parseExportLines(line), ...parseExportLines(line)], { naPublicKeys: [], executorKeys: [] });
    expect(result.failures.map(f => f.reason)).toEqual(['unknown_entry_kind', 'store_sequence_gap', 'unknown_entry_kind']);
  });
});
