import { describe, expect, it } from '@jest/globals';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  ObservationRecorder,
  OutOfBandRecordError,
  observationFromFinding,
  outOfBandCanonical,
  parseExportLines,
  parseJson,
  publicKeyFromSeed,
  seedSigner,
  signBreakGlass,
  verifyEvidenceEvents,
  verifyOutOfBandRecord,
} from '../src/index.js';
import type { ExecutorKeyInfo, OutOfBandRecord, ReconciliationFinding } from '../src/index.js';
import { generateTestKeyPair } from './helpers.js';

/**
 * The `out_of_band` conformance suite (Genesis Mesh 1.3.0), generated by the
 * Python reference and copied unchanged. The `time_bounds` and
 * `policy_history` vectors are the NA's own rules: an SDK neither admits nor
 * judges records, so they are not run here.
 */
interface Vector {
  id: string;
  kind: string;
  description: string;
  input?: Record<string, unknown>;
  model?: string;
  record?: Record<string, unknown>;
  public_key?: string;
  expected: Record<string, unknown>;
}

const raw = readFileSync(fileURLToPath(new URL('./fixtures/conformance/out_of_band.json', import.meta.url)), 'utf-8');
const suite = parseJson(raw) as { suite: string; vectors: Vector[] };
const NA_RULES = new Set(['time_bounds', 'policy_history']);

function outcome(v: Vector): Record<string, unknown> {
  switch (v.kind) {
    case 'verify_export': {
      const i = v.input!;
      const result = verifyEvidenceEvents(parseExportLines(i['lines'] as string), {
        naPublicKeys: i['na_public_keys'] as string[],
        executorKeys: i['executor_keys'] as ExecutorKeyInfo[],
        contiguous: i['contiguous'] as boolean,
      });
      const failures = [...new Map(result.failures.map(f => [`${f.store_sequence}\u0000${f.reason}`, f])).values()]
        .map(f => ({ store_sequence: f.store_sequence, reason: f.reason }))
        .sort((a, b) => (a.store_sequence ?? 0) - (b.store_sequence ?? 0) || (a.reason < b.reason ? -1 : 1));
      const counts = Object.fromEntries((['observations', 'break_glass', 'judgements', 'quarantined'] as const)
        .filter(k => result[k] !== undefined).map(k => [k, result[k]]));
      return { verified: result.verified, failures, counts };
    }
    case 'canonical_form': {
      const canonical = outOfBandCanonical(v.record!);
      return { canonical, digest: createHash('sha256').update(canonical, 'utf-8').digest('hex') };
    }
    case 'verify_record':
      return { valid: verifyOutOfBandRecord(v.record as unknown as OutOfBandRecord, [v.public_key!]) };
    default:
      throw new Error(`unknown vector kind ${v.kind}`);
  }
}

describe('out_of_band conformance vectors (v1.3.0)', () => {
  it('is the out_of_band suite', () => {
    expect(suite.suite).toBe('out_of_band');
    expect(suite.vectors.some(v => v.kind === 'verify_export')).toBe(true);
  });

  for (const v of suite.vectors.filter(vector => !NA_RULES.has(vector.kind))) {
    it(`${v.id}: ${v.description}`, () => {
      expect(outcome(v)).toEqual(v.expected);
    });
  }
});

describe('ObservationRecorder', () => {
  const { seedBase64: seed } = generateTestKeyPair();
  const signer = seedSigner(seed, 'observer-1');
  const recorder = new ObservationRecorder({ observerSovereignId: 'cloud-observer', signer });

  it('signs every field but the signature and leaves absent fields out', async () => {
    const record = await recorder.record({
      resource_id: 'kv:prod/api-key', action: 'rotate', capability: 'secret.rotate',
      changed_at: new Date('2026-01-01T00:01:00Z'), observed_at: new Date('2026-01-01T00:02:00Z'),
      source: 'cloud-activity-log', source_event_id: 'event-1', metadata: { lifetime_days: 30 },
    });
    expect(record.changed_at).toBe('2026-01-01T00:01:00Z');
    expect('version_id' in record).toBe(false);
    expect('changed_not_before' in record).toBe(false);
    expect(record.signature?.key_id).toBe('observer-1');
    expect(verifyOutOfBandRecord(record, [publicKeyFromSeed(seed)])).toBe(true);
    expect(verifyOutOfBandRecord({ ...record, action: 'delete' }, [publicKeyFromSeed(seed)])).toBe(false);
  });

  it('needs one change time, never both forms', async () => {
    const base = {
      resource_id: 'kv:prod/api-key', action: 'rotate' as const, capability: 'secret.rotate',
      source: 'log', source_event_id: 'e',
    };
    await expect(recorder.record(base)).rejects.toThrow(OutOfBandRecordError);
    await expect(recorder.record({
      ...base, changed_at: new Date(), changed_not_before: new Date(), changed_not_after: new Date(),
    })).rejects.toThrow('not both');
  });

  it('refuses secret material in metadata before signing', async () => {
    await expect(recorder.record({
      resource_id: 'kv:prod/api-key', action: 'rotate', capability: 'secret.rotate', changed_at: new Date(),
      source: 'log', source_event_id: 'e', metadata: { password: 'hunter2' },
    })).rejects.toMatchObject({ code: 'observation_secret_material' });
  });

  it('turns a reconciliation finding into a windowed observation, once per scan', () => {
    const finding: ReconciliationFinding = {
      resource_id: 'kv:prod/api-key', status: 'drifted', detail: 'cloud version 3, governed version 2',
      observed: { resource_id: 'kv:prod/api-key', exists: true, version: '3' }, recorded: null,
    };
    const options = {
      capability: 'secret.rotate',
      previousScanAt: new Date('2026-01-01T00:00:00Z'),
      scannedAt: new Date('2026-01-01T01:00:00Z'),
    };
    const input = observationFromFinding(finding, options)!;
    expect(input.action).toBe('update');
    expect(input.changed_not_before).toEqual(options.previousScanAt);
    expect(input.changed_not_after).toEqual(options.scannedAt);
    expect(input.version_id).toBe('3');
    expect(observationFromFinding(finding, options)!.source_event_id).toBe(input.source_event_id);
    expect(observationFromFinding({ ...finding, status: 'in_sync' }, options)).toBeNull();
  });
});

describe('signBreakGlass', () => {
  const { seedBase64: seed } = generateTestKeyPair();
  const signer = seedSigner(seed, 'executor-1');
  const input = {
    executor_sovereign_id: 'controller', resource_id: 'kv:prod/api-key', resource_action: 'rotate' as const,
    capability: 'secret.rotate', justification: 'incident 42: key leaked, NA unreachable',
    evaluation_request: { requested_capability: 'secret.rotate' }, evaluation_failure: 'network_error' as const,
    outcome: 'success', execution_parameters: { version_id: 'v7' },
  };

  it('records the failed request by digest only', async () => {
    const record = await signBreakGlass(input, signer);
    expect(record.evaluation_request_digest).toMatch(/^[0-9a-f]{64}$/);
    expect('evaluation_request' in record).toBe(false);
    expect(verifyOutOfBandRecord(record, [publicKeyFromSeed(seed)])).toBe(true);
  });

  it('needs a justification and refuses secret material', async () => {
    await expect(signBreakGlass({ ...input, justification: '' }, signer))
      .rejects.toMatchObject({ code: 'break_glass_malformed' });
    await expect(signBreakGlass({ ...input, execution_parameters: { client_secret: 'x' } }, signer))
      .rejects.toMatchObject({ code: 'break_glass_secret_material' });
  });
});
